## Series

In [1]:
import pandas as pd
import numpy as np

In [2]:
s = pd.Series([12, 34, 56, 78, 10])

In [3]:
s

0    12
1    34
2    56
3    78
4    10
dtype: int64

In [4]:
s[2]

np.int64(56)

In [5]:
s = pd.Series([12, 34, 56, 78, 10], index= range(100, 105))
s

100    12
101    34
102    56
103    78
104    10
dtype: int64

In [6]:
s[103]

np.int64(78)

## Dataframes

In [7]:
roll = pd.Series([1, 2, 3, 4, 5])
name = pd.Series(['geet', 'ankit', 'ravi', 'kritika', 'natasha'])
marks = pd.Series([78, 79, 67, 81, 80])

In [8]:
df = pd.DataFrame({
    'roll': roll,
    'name': name,
    'marks': marks
})

In [9]:
df

   roll     name  marks
0     1     geet     78
1     2    ankit     79
2     3     ravi     67
3     4  kritika     81
4     5  natasha     80

In [10]:
df.shape

(5, 3)

In [11]:
df.columns

Index(['roll', 'name', 'marks'], dtype='object')

In [12]:
"""
url => https://mitu.co.in/dataset

this will redirect u to drive folder containing datasets
download datasets starting with student*... eg... student.csv, student1.csv

after downloading put them into the same directory where ur jupyter notebook
files are 
""";

In [13]:
pwd

'/home/aditya/VPBKIET_Mar2_2026/Day2'

In [14]:
df = pd.read_csv("student.csv")
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [15]:
df.columns

Index(['roll', 'name', 'class', 'marks', 'age'], dtype='object')

In [16]:
df.shape

(10, 5)

In [17]:
# student1.csv

In [18]:
df = pd.read_csv("student1.csv")
df

    1     anil  TE  56.77  22
0   2     amit  TE  59.77  21
1   3   aniket  BE  76.88  19
2   4  ajinkya  TE  69.66  20
3   5     asha  TE  63.28  20
4   6   ayesha  BE  49.55  20
5   7     amar  BE  65.34  19
6   8    amita  BE  68.33  23
7   9     amol  TE  56.75  20
8  10    anmol  BE  78.66  21

In [19]:
col = ["id", "name", "class", "grade", "age"]

In [20]:
df = pd.read_csv("student1.csv", names= col)
df

   id     name class  grade  age
0   1     anil    TE  56.77   22
1   2     amit    TE  59.77   21
2   3   aniket    BE  76.88   19
3   4  ajinkya    TE  69.66   20
4   5     asha    TE  63.28   20
5   6   ayesha    BE  49.55   20
6   7     amar    BE  65.34   19
7   8    amita    BE  68.33   23
8   9     amol    TE  56.75   20
9  10    anmol    BE  78.66   21

In [21]:
# student3.tsv

In [22]:
df = pd.read_csv("student3.tsv", sep = '\t')
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [23]:
df = pd.read_csv("student.csv")
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   roll    10 non-null     int64
 1   name    10 non-null     object
 2   class   10 non-null     object
 3   marks   10 non-null     float64
 4   age     10 non-null     int64
dtypes: float64(1), int64(2), object(2)
memory usage: 532.0+ bytes

In [25]:
df.describe()

           roll      marks        age
count  10.00000  10.000000  10.000000
mean    5.50000  64.499000  20.500000
std     3.02765   9.207179   1.269296
min     1.00000  49.550000  19.000000
25%     3.25000  57.520000  20.000000
50%     5.50000  64.310000  20.000000
75%     7.75000  69.327500  21.000000
max    10.00000  78.660000  23.000000

In [26]:
df.head()

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20

In [27]:
df.head(3)

   roll    name class  marks  age
0     1    anil    TE  56.77   22
1     2    amit    TE  59.77   21
2     3  aniket    BE  76.88   19

In [28]:
df.tail()

   roll    name class  marks  age
5     6  ayesha    BE  49.55   20
6     7    amar    BE  65.34   19
7     8   amita    BE  68.33   23
8     9    amol    TE  56.75   20
9    10   anmol    BE  78.66   21

In [29]:
df.values

array([[1, 'anil', 'TE', 56.77, 22],
       [2, 'amit', 'TE', 59.77, 21],
       [3, 'aniket', 'BE', 76.88, 19],
       [4, 'ajinkya', 'TE', 69.66, 20],
       [5, 'asha', 'TE', 63.28, 20],
       [6, 'ayesha', 'BE', 49.55, 20],
       [7, 'amar', 'BE', 65.34, 19],
       [8, 'amita', 'BE', 68.33, 23],
       [9, 'amol', 'TE', 56.75, 20],
       [10, 'anmol', 'BE', 78.66, 21]], dtype=object)

In [30]:
df.T

,0,1,2,3,4,5,6,7,8,9
roll,1,2,3,4,5,6,7,8,9,10
name,anil,amit,aniket,ajinkya,asha,ayesha,amar,amita,amol,anmol
class,TE,TE,BE,TE,TE,BE,BE,BE,TE,BE
marks,56.77,59.77,76.88,69.66,63.28,49.55,65.34,68.33,56.75,78.66
age,22,21,19,20,20,20,19,23,20,21

In [31]:
# slicing

In [32]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [33]:
df.iloc[3:6, 1:4]

      name class  marks
3  ajinkya    TE  69.66
4     asha    TE  63.28
5   ayesha    BE  49.55

In [34]:
df.iloc[[3, 4, 6], 0:2]

   roll     name
3     4  ajinkya
4     5     asha
6     7     amar

In [35]:
df.iloc[[2, 3, 4, 6, 7], [1, 3 , 4]]

      name  marks  age
2   aniket  76.88   19
3  ajinkya  69.66   20
4     asha  63.28   20
6     amar  65.34   19
7    amita  68.33   23

In [36]:
df.loc[:, 'class']

0    TE
1    TE
2    BE
3    TE
4    TE
5    BE
6    BE
7    BE
8    TE
9    BE
Name: class, dtype: object

In [37]:
type(df.loc[:, 'class'])

pandas.core.series.Series

In [38]:
df['class']

0    TE
1    TE
2    BE
3    TE
4    TE
5    BE
6    BE
7    BE
8    TE
9    BE
Name: class, dtype: object

In [39]:
df[['class', 'name']]

  class     name
0    TE     anil
1    TE     amit
2    BE   aniket
3    TE  ajinkya
4    TE     asha
5    BE   ayesha
6    BE     amar
7    BE    amita
8    TE     amol
9    BE    anmol

In [40]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [41]:
df.drop(3)

   roll    name class  marks  age
0     1    anil    TE  56.77   22
1     2    amit    TE  59.77   21
2     3  aniket    BE  76.88   19
4     5    asha    TE  63.28   20
5     6  ayesha    BE  49.55   20
6     7    amar    BE  65.34   19
7     8   amita    BE  68.33   23
8     9    amol    TE  56.75   20
9    10   anmol    BE  78.66   21

In [42]:
df.drop([3, 4, 6])

   roll    name class  marks  age
0     1    anil    TE  56.77   22
1     2    amit    TE  59.77   21
2     3  aniket    BE  76.88   19
5     6  ayesha    BE  49.55   20
7     8   amita    BE  68.33   23
8     9    amol    TE  56.75   20
9    10   anmol    BE  78.66   21

In [43]:
df.drop('class', axis = 1)

   roll     name  marks  age
0     1     anil  56.77   22
1     2     amit  59.77   21
2     3   aniket  76.88   19
3     4  ajinkya  69.66   20
4     5     asha  63.28   20
5     6   ayesha  49.55   20
6     7     amar  65.34   19
7     8    amita  68.33   23
8     9     amol  56.75   20
9    10    anmol  78.66   21

In [44]:
# function and methods on series

In [45]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [46]:
df['marks'].mean()

np.float64(64.499)

In [47]:
df['marks'].sum()

np.float64(644.9899999999999)

In [48]:
df['name'].str.upper()

0       ANIL
1       AMIT
2     ANIKET
3    AJINKYA
4       ASHA
5     AYESHA
6       AMAR
7      AMITA
8       AMOL
9      ANMOL
Name: name, dtype: object

In [49]:
df['name'].str.startswith('an')

0     True
1    False
2     True
3    False
4    False
5    False
6    False
7    False
8    False
9     True
Name: name, dtype: bool

In [50]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [51]:
df['roll'] = df['roll'] + 100

In [52]:
df

   roll     name class  marks  age
0   101     anil    TE  56.77   22
1   102     amit    TE  59.77   21
2   103   aniket    BE  76.88   19
3   104  ajinkya    TE  69.66   20
4   105     asha    TE  63.28   20
5   106   ayesha    BE  49.55   20
6   107     amar    BE  65.34   19
7   108    amita    BE  68.33   23
8   109     amol    TE  56.75   20
9   110    anmol    BE  78.66   21

In [53]:
gender = ['m', 'm', 'm', 'm', 'f', 'f', 'm', 'f', 'm', 'm']

In [54]:
df['gender'] = gender

In [55]:
df

   roll     name class  marks  age gender
0   101     anil    TE  56.77   22      m
1   102     amit    TE  59.77   21      m
2   103   aniket    BE  76.88   19      m
3   104  ajinkya    TE  69.66   20      m
4   105     asha    TE  63.28   20      f
5   106   ayesha    BE  49.55   20      f
6   107     amar    BE  65.34   19      m
7   108    amita    BE  68.33   23      f
8   109     amol    TE  56.75   20      m
9   110    anmol    BE  78.66   21      m

In [ ]:
# create a column ->   cgpa
# values should be->   marks/10 + 1.5

In [56]:
df['cgpa'] = df['marks'] / 10 + 1.5

In [57]:
df

   roll     name class  marks  age gender   cgpa
0   101     anil    TE  56.77   22      m  7.177
1   102     amit    TE  59.77   21      m  7.477
2   103   aniket    BE  76.88   19      m  9.188
3   104  ajinkya    TE  69.66   20      m  8.466
4   105     asha    TE  63.28   20      f  7.828
5   106   ayesha    BE  49.55   20      f  6.455
6   107     amar    BE  65.34   19      m  8.034
7   108    amita    BE  68.33   23      f  8.333
8   109     amol    TE  56.75   20      m  7.175
9   110    anmol    BE  78.66   21      m  9.366

In [58]:
gr = df.groupby('class')

In [59]:
gr.groups

{'BE': [2, 5, 6, 7, 9], 'TE': [0, 1, 3, 4, 8]}

In [60]:
gr['marks'].mean()

class
BE    67.752
TE    61.246
Name: marks, dtype: float64

In [61]:
gr.get_group('BE')

   roll    name class  marks  age gender   cgpa
2   103  aniket    BE  76.88   19      m  9.188
5   106  ayesha    BE  49.55   20      f  6.455
6   107    amar    BE  65.34   19      m  8.034
7   108   amita    BE  68.33   23      f  8.333
9   110   anmol    BE  78.66   21      m  9.366

In [62]:
df

   roll     name class  marks  age gender   cgpa
0   101     anil    TE  56.77   22      m  7.177
1   102     amit    TE  59.77   21      m  7.477
2   103   aniket    BE  76.88   19      m  9.188
3   104  ajinkya    TE  69.66   20      m  8.466
4   105     asha    TE  63.28   20      f  7.828
5   106   ayesha    BE  49.55   20      f  6.455
6   107     amar    BE  65.34   19      m  8.034
7   108    amita    BE  68.33   23      f  8.333
8   109     amol    TE  56.75   20      m  7.175
9   110    anmol    BE  78.66   21      m  9.366

In [63]:
df.sort_values(by = 'marks')

   roll     name class  marks  age gender   cgpa
5   106   ayesha    BE  49.55   20      f  6.455
8   109     amol    TE  56.75   20      m  7.175
0   101     anil    TE  56.77   22      m  7.177
1   102     amit    TE  59.77   21      m  7.477
4   105     asha    TE  63.28   20      f  7.828
6   107     amar    BE  65.34   19      m  8.034
7   108    amita    BE  68.33   23      f  8.333
3   104  ajinkya    TE  69.66   20      m  8.466
2   103   aniket    BE  76.88   19      m  9.188
9   110    anmol    BE  78.66   21      m  9.366

In [64]:
df.sort_values(by = 'marks', ascending= False)

   roll     name class  marks  age gender   cgpa
9   110    anmol    BE  78.66   21      m  9.366
2   103   aniket    BE  76.88   19      m  9.188
3   104  ajinkya    TE  69.66   20      m  8.466
7   108    amita    BE  68.33   23      f  8.333
6   107     amar    BE  65.34   19      m  8.034
4   105     asha    TE  63.28   20      f  7.828
1   102     amit    TE  59.77   21      m  7.477
0   101     anil    TE  56.77   22      m  7.177
8   109     amol    TE  56.75   20      m  7.175
5   106   ayesha    BE  49.55   20      f  6.455

In [65]:
# boolean filtering

In [67]:
df[df['marks'] > 65]

   roll     name class  marks  age gender   cgpa
2   103   aniket    BE  76.88   19      m  9.188
3   104  ajinkya    TE  69.66   20      m  8.466
6   107     amar    BE  65.34   19      m  8.034
7   108    amita    BE  68.33   23      f  8.333
9   110    anmol    BE  78.66   21      m  9.366

In [68]:
df[(df['marks'] > 65) & (df['class'] == 'BE')]

   roll    name class  marks  age gender   cgpa
2   103  aniket    BE  76.88   19      m  9.188
6   107    amar    BE  65.34   19      m  8.034
7   108   amita    BE  68.33   23      f  8.333
9   110   anmol    BE  78.66   21      m  9.366

In [69]:
df

   roll     name class  marks  age gender   cgpa
0   101     anil    TE  56.77   22      m  7.177
1   102     amit    TE  59.77   21      m  7.477
2   103   aniket    BE  76.88   19      m  9.188
3   104  ajinkya    TE  69.66   20      m  8.466
4   105     asha    TE  63.28   20      f  7.828
5   106   ayesha    BE  49.55   20      f  6.455
6   107     amar    BE  65.34   19      m  8.034
7   108    amita    BE  68.33   23      f  8.333
8   109     amol    TE  56.75   20      m  7.175
9   110    anmol    BE  78.66   21      m  9.366

In [72]:
df.drop(['gender', 'cgpa'], axis = 1, inplace = True)

In [73]:
df

   roll     name class  marks  age
0   101     anil    TE  56.77   22
1   102     amit    TE  59.77   21
2   103   aniket    BE  76.88   19
3   104  ajinkya    TE  69.66   20
4   105     asha    TE  63.28   20
5   106   ayesha    BE  49.55   20
6   107     amar    BE  65.34   19
7   108    amita    BE  68.33   23
8   109     amol    TE  56.75   20
9   110    anmol    BE  78.66   21

In [74]:
# create a dataframe called df1 having columns -> roll, gender, cgpa
# roll column should be having same values as that of roll column of df

In [77]:
df1 = pd.DataFrame({
    'roll': df['roll'],
    'gender': gender,
    'cgpa': df['marks']/10 + 1.5
})

In [78]:
df1

   roll gender   cgpa
0   101      m  7.177
1   102      m  7.477
2   103      m  9.188
3   104      m  8.466
4   105      f  7.828
5   106      f  6.455
6   107      m  8.034
7   108      f  8.333
8   109      m  7.175
9   110      m  9.366